/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1b1b',
        'surface-container': '#1f1f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#bccabb',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#303030',
        outline: '#869486',
        'outline-variant': '#3d4a3e',
        'surface-tint': '#4de082',
        primary: '#6bfb9a',
        'on-primary': '#003919',
        'primary-container': '#4ade80',
        'on-primary-container': '#005e2d',
        'inverse-primary': '#006d36',
        secondary: '#d0bcff',
        'on-secondary': '#3c0091',
        'secondary-container': '#571bc1',
        'on-secondary-container': '#c4abff',
        tertiary: '#ffd8c6',
        'on-tertiary': '#552100',
        'tertiary-container': '#ffb38b',
        'on-tertiary-container': '#883900',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#131313',
        'on-background': '#e2e2e2',
        'surface-variant': '#353535'
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        mono: ['Space Grotesk', 'monospace'],
      },
      spacing: {
        'grid-margin': '4rem',
        'grid-gutter': '1.5rem',
        'unit': '4px',
        'section-gap': '10rem',
      },
    },
  },
  plugins: [],
}
